In [4]:
import pandas as pd
import numpy as np

df = pd.read_csv("/content/sample_data/VSRR_Provisional_Drug_Overdose_Death_Counts_20260214.csv")
df.head()

,State,Year,Month,Period,Indicator,Data Value,Percent Complete,Percent Pending Investigation,State Name,Footnote,Footnote Symbol,Predicted Value
0,AK,2015,January,12 month-ending,Cocaine (T40.5),NaN,100,0.0,Alaska,Numbers may differ from published reports usin...,**,NaN
1,AK,2015,February,12 month-ending,Cocaine (T40.5),NaN,100,0.0,Alaska,Numbers may differ from published reports usin...,**,NaN
2,AK,2015,March,12 month-ending,Cocaine (T40.5),NaN,100,0.0,Alaska,Numbers may differ from published reports usin...,**,NaN
3,AK,2015,April,12 month-ending,Cocaine (T40.5),NaN,100,0.0,Alaska,Numbers may differ from published reports usin...,**,NaN
4,AK,2015,May,12 month-ending,Cocaine (T40.5),NaN,100,0.0,Alaska,Numbers may differ from published reports usin...,**,NaN

In [28]:
df_cleaned = df.dropna()
# Remove duplicate rows
df_cleaned = df_cleaned.drop_duplicates()
# Optionally, reset index
df_cleaned = df_cleaned.reset_index(drop=True)

# Combine 'Year' and 'Month' to create a new 'Date' column and dropping unnecessary data
df_cleaned['Date'] = pd.to_datetime(df_cleaned['Year'].astype(str) + '-' + df_cleaned['Month'] + '-01')
df_cleaned.drop(['Year', 'Month','Period','Footnote','Footnote Symbol'], axis=1, inplace=True)

df_cleaned_filtered = df_cleaned[(df_cleaned['Percent Complete'] == 100) & (df_cleaned['Percent Pending Investigation']< 0.3)]

# data index fixing
columns = df_cleaned_filtered.columns.tolist()
columns.remove('Date')
indicator_index = columns.index('Indicator')
columns.insert(indicator_index + 1, 'Date')
df_cleaned_filtered = df_cleaned_filtered[columns]
df_cleaned_filtered = df_cleaned_filtered.rename(columns={'Data Value': 'Death Count'})
df_cleaned_filtered

,State,Indicator,Date,Death Count,Percent Complete,Percent Pending Investigation,State Name,Predicted Value
0,AK,Cocaine (T40.5),2016-04-01,11,100,0.000000,Alaska,11
1,AK,Cocaine (T40.5),2016-05-01,11,100,0.000000,Alaska,11
2,AK,Cocaine (T40.5),2016-06-01,11,100,0.000000,Alaska,11
3,AK,Cocaine (T40.5),2016-07-01,13,100,0.000000,Alaska,13
4,AK,Cocaine (T40.5),2016-08-01,12,100,0.023386,Alaska,12

KeyError: 'Year'